### 회원가입
POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email": "1ddas1@gamil.com",
  "nickname": "a2태1현1",
  "password": "12345678@",
  "passwordConfirmation":"12345678@"
}


### 로그인
POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email": "1ddas1@gamil.com",
  "password": "12345678@"
}

### 리프레쉬 토큰
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "string"
}