### 내정보 조회
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzgzNDA1ODMwLCJleHAiOjE3ODM0MDk0MzB9.9JwbFY2Pt0ZXHN_8_vcGtdAglFwdOiGfLlzKc6kInaU


### 프로필 사진 수정
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzgzNDA1ODMwLCJleHAiOjE3ODM0MDk0MzB9.9JwbFY2Pt0ZXHN_8_vcGtdAglFwdOiGfLlzKc6kInaU

{
  "image": "https://example.com/...1"
}


### 비밀번호 수정
PATCH http://localhost:3000/users/me/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzgzNDA1ODMwLCJleHAiOjE3ODM0MDk0MzB9.9JwbFY2Pt0ZXHN_8_vcGtdAglFwdOiGfLlzKc6kInaU

{
  "passwordConfirmation": "123456789@",
  "password": "123456789@",
  "currentPassword": "12345678@"
}

### 내 상품 조회
GET http://localhost:3000/users/me/products?page=1&pageSize=10&keyword=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzgzNDA1ODMwLCJleHAiOjE3ODM0MDk0MzB9.9JwbFY2Pt0ZXHN_8_vcGtdAglFwdOiGfLlzKc6kInaU


### 
GET http://localhost:3000/users/me/favorites?page=1&pageSize=10&keyword=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzgzNDA1ODMwLCJleHAiOjE3ODM0MDk0MzB9.9JwbFY2Pt0ZXHN_8_vcGtdAglFwdOiGfLlzKc6kInaU